"""store the raw ranking score alongside the calibrated probability

Revision ID: 071427df1cc0
Revises: a2b191c521c0
Create Date: 2026-09-20 19:14:30.974541
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '071427df1cc0'
down_revision = 'a2b191c521c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_orders', sa.Column('ranking_score', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot_orders', 'ranking_score')
    # ### end Alembic commands ###
