"""initial schema

Revision ID: 431db7e3d18a
Revises: 
Create Date: 2026-09-20 04:28:56.092787
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '431db7e3d18a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(event_type) > 0', name='ck_audit_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_session_id'), 'audit_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_events_subject_id'), 'audit_events', ['subject_id'], unique=False)
    op.create_index('ix_audit_session', 'audit_events', ['session_id', 'created_at'], unique=False)
    op.create_table('guest_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('investigations_today', sa.Integer(), nullable=False),
    sa.Column('quota_window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_guest_sessions_expires_at'), 'guest_sessions', ['expires_at'], unique=False)
    op.create_table('order_features',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=False),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_state', sa.String(length=8), nullable=True),
    sa.Column('seller_state', sa.String(length=8), nullable=True),
    sa.Column('product_category', sa.String(length=64), nullable=True),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('total_freight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_features_customer_state'), 'order_features', ['customer_state'], unique=False)
    op.create_index(op.f('ix_order_features_order_delivered_carrier_date'), 'order_features', ['order_delivered_carrier_date'], unique=False)
    op.create_index(op.f('ix_order_features_product_category'), 'order_features', ['product_category'], unique=False)
    op.create_index(op.f('ix_order_features_seller_state'), 'order_features', ['seller_state'], unique=False)
    op.create_index(op.f('ix_order_features_split'), 'order_features', ['split'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('orders_in_transit', sa.Integer(), nullable=False),
    sa.Column('orders_pre_deadline', sa.Integer(), nullable=False),
    sa.Column('orders_overdue', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'insufficient_evidence', 'failed', name='investigation_status'), nullable=False),
    sa.Column('prediction_as_of', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['guest_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_index(op.f('ix_investigations_order_id'), 'investigations', ['order_id'], unique=False)
    op.create_index('ix_investigations_session', 'investigations', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_session_id'), 'investigations', ['session_id'], unique=False)
    op.create_table('order_outcomes',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_features.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_outcomes_is_late'), 'order_outcomes', ['is_late'], unique=False)
    op.create_index(op.f('ix_order_outcomes_order_delivered_customer_date'), 'order_outcomes', ['order_delivered_customer_date'], unique=False)
    op.create_table('snapshot_orders',
    sa.Column('snapshot_id', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('days_in_transit', sa.Float(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=8), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_features.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'order_id')
    )
    op.create_index('ix_snapshot_orders_queue', 'snapshot_orders', ['snapshot_id', 'is_overdue', 'risk_probability'], unique=False)
    op.create_table('proposals',
    sa.Column('proposal_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='proposal_status'), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['guest_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id'),
    sa.UniqueConstraint('investigation_id', name='uq_proposal_investigation')
    )
    op.create_index(op.f('ix_proposals_investigation_id'), 'proposals', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_proposals_session_id'), 'proposals', ['session_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('proposal_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['guest_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('proposal_id', name='uq_ticket_proposal')
    )
    op.create_index('ix_tickets_session', 'tickets', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tickets_session_id'), 'tickets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_session_id'), table_name='tickets')
    op.drop_index('ix_tickets_session', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_session_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_investigation_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_snapshot_orders_queue', table_name='snapshot_orders')
    op.drop_table('snapshot_orders')
    op.drop_index(op.f('ix_order_outcomes_order_delivered_customer_date'), table_name='order_outcomes')
    op.drop_index(op.f('ix_order_outcomes_is_late'), table_name='order_outcomes')
    op.drop_table('order_outcomes')
    op.drop_index(op.f('ix_investigations_session_id'), table_name='investigations')
    op.drop_index('ix_investigations_session', table_name='investigations')
    op.drop_index(op.f('ix_investigations_order_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_order_features_split'), table_name='order_features')
    op.drop_index(op.f('ix_order_features_seller_state'), table_name='order_features')
    op.drop_index(op.f('ix_order_features_product_category'), table_name='order_features')
    op.drop_index(op.f('ix_order_features_order_delivered_carrier_date'), table_name='order_features')
    op.drop_index(op.f('ix_order_features_customer_state'), table_name='order_features')
    op.drop_table('order_features')
    op.drop_index(op.f('ix_guest_sessions_expires_at'), table_name='guest_sessions')
    op.drop_table('guest_sessions')
    op.drop_index('ix_audit_session', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_subject_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
